import prisma from "@/app/lib/db";

// Source: tbl_cities (203 rows). NOTE: ids 86 and 87 are both
// "Kharan" / "Balochistan" — an exact duplicate already present in the
// source data. Kept as two separate rows (not deduplicated) since removing
// one could break any existing foreign key referencing id 87 specifically.
// City id 140 ("Others") has an empty province in the source data, kept as
// an empty string rather than guessing a province for it.
const cities: { id: number; cityName: string; province: string }[] = [
  { id: 1, cityName: "Abbottabad", province: "KPK" },
  { id: 2, cityName: "Adezai", province: "KPK" },
  { id: 3, cityName: "Akora Khattak", province: "KPK" },
  { id: 4, cityName: "Alpuri", province: "KPK" },
  { id: 5, cityName: "Arang Khel", province: "Azad Kashmir" },
  { id: 6, cityName: "Attock", province: "Punjab" },
  { id: 7, cityName: "Awaran", province: "Balochistan" },
  { id: 8, cityName: "Ayubia", province: "KPK" },
  { id: 9, cityName: "Azad Pattan", province: "Azad Kashmir" },
  { id: 10, cityName: "Badin", province: "Sindh" },
  { id: 11, cityName: "Bagh", province: "Azad Kashmir" },
  { id: 12, cityName: "Bahawalnagar", province: "Punjab" },
  { id: 13, cityName: "Bahawalpur", province: "Punjab" },
  { id: 14, cityName: "Banda Daud Shah", province: "KPK" },
  { id: 15, cityName: "Bannu", province: "KPK" },
  { id: 16, cityName: "Barkhan", province: "Balochistan" },
  { id: 17, cityName: "Batkhela", province: "KPK" },
  { id: 18, cityName: "Battagram", province: "KPK" },
  { id: 19, cityName: "Bhakkar", province: "Punjab" },
  { id: 20, cityName: "Bhimber", province: "Azad Kashmir" },
  { id: 21, cityName: "Bhirkan", province: "Sindh" },
  { id: 22, cityName: "Birote", province: "KPK" },
  { id: 23, cityName: "Chagai", province: "Balochistan" },
  { id: 24, cityName: "Chak", province: "Sindh" },
  { id: 25, cityName: "Chakdara", province: "KPK" },
  { id: 26, cityName: "Chakswari", province: "Azad Kashmir" },
  { id: 27, cityName: "Chakwal", province: "Punjab" },
  { id: 28, cityName: "Chaman", province: "Balochistan" },
  { id: 29, cityName: "Charsadda", province: "KPK" },
  { id: 30, cityName: "Chiniot", province: "Punjab" },
  { id: 31, cityName: "Chitral", province: "KPK" },
  { id: 32, cityName: "Dadu", province: "Sindh" },
  { id: 33, cityName: "Dadyal", province: "Azad Kashmir" },
  { id: 34, cityName: "Daggar", province: "KPK" },
  { id: 35, cityName: "Dargai", province: "KPK" },
  { id: 36, cityName: "Darya Khan", province: "KPK" },
  { id: 37, cityName: "Dera Allah Yar", province: "Balochistan" },
  { id: 38, cityName: "Dera Bugti", province: "Balochistan" },
  { id: 39, cityName: "Dera Ghazi Khan", province: "Punjab" },
  { id: 40, cityName: "Dera Ismail Khan", province: "KPK" },
  { id: 41, cityName: "Dera Murad Jamali", province: "Balochistan" },
  { id: 42, cityName: "Digri", province: "Sindh" },
  { id: 43, cityName: "Diplo", province: "Sindh" },
  { id: 44, cityName: "Dir", province: "KPK" },
  { id: 45, cityName: "Doaba", province: "KPK" },
  { id: 46, cityName: "Dokri", province: "Sindh" },
  { id: 47, cityName: "Drosh", province: "KPK" },
  { id: 48, cityName: "Faisalabad", province: "Punjab" },
  { id: 49, cityName: "Ghotki", province: "Sindh" },
  { id: 50, cityName: "Gujranwala", province: "Punjab" },
  { id: 51, cityName: "Gujrat", province: "Punjab" },
  { id: 52, cityName: "Gwader", province: "Balochistan" },
  { id: 53, cityName: "Haala", province: "Sindh" },
  { id: 54, cityName: "Hafizabad", province: "Punjab" },
  { id: 55, cityName: "Hajira", province: "Azad Kashmir" },
  { id: 56, cityName: "Hangu", province: "KPK" },
  { id: 57, cityName: "Haripur", province: "KPK" },
  { id: 58, cityName: "Harnai", province: "Balochistan" },
  { id: 59, cityName: "Hattian Bala", province: "Azad Kashmir" },
  { id: 60, cityName: "Haveli", province: "Azad Kashmir" },
  { id: 61, cityName: "Hub", province: "Balochistan" },
  { id: 62, cityName: "Hyderabad", province: "Sindh" },
  { id: 63, cityName: "Islamabad", province: "Punjab" },
  { id: 64, cityName: "Islamkot", province: "Sindh" },
  { id: 65, cityName: "Jacobabad", province: "Sindh" },
  { id: 66, cityName: "Jafarabad", province: "Balochistan" },
  { id: 67, cityName: "Jamshoro", province: "Sindh" },
  { id: 68, cityName: "Jhal Magsi", province: "Balochistan" },
  { id: 69, cityName: "Jhang", province: "Punjab" },
  { id: 70, cityName: "Jhelum", province: "Punjab" },
  { id: 71, cityName: "Jungshahi", province: "Sindh" },
  { id: 72, cityName: "Kacchi", province: "Balochistan" },
  { id: 73, cityName: "Kalat", province: "Balochistan" },
  { id: 74, cityName: "Kandhkot", province: "Sindh" },
  { id: 75, cityName: "Kandiaro", province: "Sindh" },
  { id: 76, cityName: "Karachi", province: "Sindh" },
  { id: 77, cityName: "Karak", province: "KPK" },
  { id: 78, cityName: "Kashmore", province: "Sindh" },
  { id: 79, cityName: "Kasur", province: "Punjab" },
  { id: 80, cityName: "Kech", province: "Balochistan" },
  { id: 81, cityName: "Kel", province: "Azad Kashmir" },
  { id: 82, cityName: "Keran", province: "Azad Kashmir" },
  { id: 83, cityName: "Keti Bandar", province: "Sindh" },
  { id: 84, cityName: "Khairpur", province: "Sindh" },
  { id: 85, cityName: "Khanewal", province: "Punjab" },
  { id: 86, cityName: "Kharan", province: "Balochistan" },
  { id: 87, cityName: "Kharan", province: "Balochistan" },
  { id: 88, cityName: "Khushab", province: "Punjab" },
  { id: 89, cityName: "Khuzdar", province: "Balochistan" },
  { id: 90, cityName: "Killa Abdullah", province: "Balochistan" },
  { id: 91, cityName: "Killa Saifullah", province: "Balochistan" },
  { id: 92, cityName: "Kohat", province: "KPK" },
  { id: 93, cityName: "Kohlu", province: "Balochistan" },
  { id: 94, cityName: "Kotli", province: "Azad Kashmir" },
  { id: 95, cityName: "Kotri", province: "Sindh" },
  { id: 96, cityName: "Kulachi", province: "KPK" },
  { id: 97, cityName: "Lahore", province: "Punjab" },
  { id: 98, cityName: "Lakki Marwat", province: "KPK" },
  { id: 99, cityName: "Larkana", province: "Sindh" },
  { id: 100, cityName: "Lasbela", province: "Balochistan" },
  { id: 101, cityName: "Latamber", province: "KPK" },
  { id: 102, cityName: "Layyah", province: "Punjab" },
  { id: 103, cityName: "Leepa Valley", province: "Azad Kashmir" },
  { id: 104, cityName: "Lehri", province: "Balochistan" },
  { id: 105, cityName: "Lodhran", province: "Punjab" },
  { id: 106, cityName: "Loralai", province: "Balochistan" },
  { id: 107, cityName: "Madyan", province: "KPK" },
  { id: 108, cityName: "Mandi Bahauddin", province: "Punjab" },
  { id: 109, cityName: "Mansehra", province: "KPK" },
  { id: 110, cityName: "Mardan", province: "KPK" },
  { id: 111, cityName: "Mastuj", province: "KPK" },
  { id: 112, cityName: "Mastung", province: "Balochistan" },
  { id: 113, cityName: "Matiari", province: "Sindh" },
  { id: 114, cityName: "Mehar", province: "Sindh" },
  { id: 115, cityName: "Mehrabpur", province: "Sindh" },
  { id: 116, cityName: "Mianwali", province: "Punjab" },
  { id: 117, cityName: "Mingora", province: "KPK" },
  { id: 118, cityName: "Mirpur", province: "Azad Kashmir" },
  { id: 119, cityName: "Mirpur Khas", province: "Sindh" },
  { id: 120, cityName: "Mithani", province: "Sindh" },
  { id: 121, cityName: "Mithi", province: "Sindh" },
  { id: 122, cityName: "Moro", province: "Sindh" },
  { id: 123, cityName: "Multan", province: "Punjab" },
  { id: 124, cityName: "Musakhel", province: "Balochistan" },
  { id: 125, cityName: "Muzaffargarh", province: "Punjab" },
  { id: 126, cityName: "Muzzafarabad", province: "Azad Kashmir" },
  { id: 127, cityName: "Nagarparkar", province: "Sindh" },
  { id: 128, cityName: "Nankana Sahib", province: "Punjab" },
  { id: 129, cityName: "Narowal", province: "Punjab" },
  { id: 130, cityName: "Nasirabad", province: "Balochistan" },
  { id: 131, cityName: "Naudero", province: "Sindh" },
  { id: 132, cityName: "Naushahro Feroze", province: "Sindh" },
  { id: 133, cityName: "Naushara", province: "Sindh" },
  { id: 134, cityName: "Nawabshah", province: "Sindh" },
  { id: 135, cityName: "Nazimabad", province: "Sindh" },
  { id: 136, cityName: "Neelum Valley", province: "Azad Kashmir" },
  { id: 137, cityName: "Noshki", province: "Balochistan" },
  { id: 138, cityName: "Nowshera", province: "KPK" },
  { id: 139, cityName: "Okara", province: "Punjab" },
  { id: 140, cityName: "Others", province: "" },
  { id: 141, cityName: "Pabbi", province: "KPK" },
  { id: 142, cityName: "Paharpur", province: "KPK" },
  { id: 143, cityName: "Pakpattan", province: "Punjab" },
  { id: 144, cityName: "Pallandri", province: "Azad Kashmir" },
  { id: 145, cityName: "Panjgur", province: "Balochistan" },
  { id: 146, cityName: "Pasni", province: "Balochistan" },
  { id: 147, cityName: "Peshawar", province: "KPK" },
  { id: 148, cityName: "Pishin", province: "Balochistan" },
  { id: 149, cityName: "Poonch", province: "Azad Kashmir" },
  { id: 150, cityName: "Qambar", province: "Sindh" },
  { id: 151, cityName: "Qasimabad", province: "Sindh" },
  { id: 152, cityName: "Quetta", province: "Balochistan" },
  { id: 153, cityName: "Rahim Yar Khan", province: "Punjab" },
  { id: 154, cityName: "Rajanpur", province: "Punjab" },
  { id: 155, cityName: "Rajo Khanani", province: "Sindh" },
  { id: 156, cityName: "Ranipur", province: "Sindh" },
  { id: 157, cityName: "Ratodero", province: "Sindh" },
  { id: 158, cityName: "Rawalkot", province: "Azad Kashmir" },
  { id: 159, cityName: "Rawalpindi", province: "Punjab" },
  { id: 160, cityName: "Rohri", province: "Sindh" },
  { id: 161, cityName: "Sahiwal", province: "Punjab" },
  { id: 162, cityName: "Saidu Sharif", province: "KPK" },
  { id: 163, cityName: "Sakrand", province: "Sindh" },
  { id: 164, cityName: "Sanghar", province: "Sindh" },
  { id: 165, cityName: "Sargodha", province: "Punjab" },
  { id: 166, cityName: "Sehna", province: "Azad Kashmir" },
  { id: 167, cityName: "Shahbandar", province: "Sindh" },
  { id: 168, cityName: "Shahdadkot", province: "Sindh" },
  { id: 169, cityName: "Shahdadpur", province: "Sindh" },
  { id: 170, cityName: "Shahpur Chakar", province: "Sindh" },
  { id: 171, cityName: "Sharda", province: "Azad Kashmir" },
  { id: 172, cityName: "Sheikhupura", province: "Punjab" },
  { id: 173, cityName: "Sherani", province: "Balochistan" },
  { id: 174, cityName: "Shewa Adda", province: "KPK" },
  { id: 175, cityName: "Shikarpaur", province: "Sindh" },
  { id: 176, cityName: "Shorkot", province: "KPK" },
  { id: 177, cityName: "Sialkot", province: "Punjab" },
  { id: 178, cityName: "Sibi", province: "Balochistan" },
  { id: 179, cityName: "Sihbatpur", province: "Balochistan" },
  { id: 180, cityName: "Sughanoti", province: "Azad Kashmir" },
  { id: 181, cityName: "Sukkur", province: "Sindh" },
  { id: 182, cityName: "Swabi", province: "KPK" },
  { id: 183, cityName: "Swat", province: "KPK" },
  { id: 184, cityName: "Tando Adam Khan", province: "Sindh" },
  { id: 185, cityName: "Tando Allahyar", province: "Sindh" },
  { id: 186, cityName: "Tando Muhammad Khan", province: "Sindh" },
  { id: 187, cityName: "Tangi", province: "KPK" },
  { id: 188, cityName: "Tangwani", province: "Sindh" },
  { id: 189, cityName: "Tank", province: "KPK" },
  { id: 190, cityName: "Taobet", province: "Azad Kashmir" },
  { id: 191, cityName: "Thall", province: "KPK" },
  { id: 192, cityName: "Thatta", province: "Sindh" },
  { id: 193, cityName: "Timergara", province: "KPK" },
  { id: 194, cityName: "Toba Tek Singh", province: "Punjab" },
  { id: 195, cityName: "Tordher", province: "KPK" },
  { id: 196, cityName: "Turbat", province: "Balochistan" },
  { id: 197, cityName: "Umerkot", province: "Sindh" },
  { id: 198, cityName: "Usta Muhammad", province: "Balochistan" },
  { id: 199, cityName: "Vehari", province: "Punjab" },
  { id: 200, cityName: "Warah", province: "Sindh" },
  { id: 201, cityName: "Washuk", province: "Balochistan" },
  { id: 202, cityName: "Zhob", province: "Balochistan" },
  { id: 203, cityName: "Ziarat", province: "Balochistan" },
];

export async function seedCities() {
  const result = await prisma.city.createMany({
    data: cities,
    skipDuplicates: true,
  });
  console.log(`Seeded ${result.count} cities.`);
}

if (require.main === module) {
  seedCities()
    .catch((err) => {
      console.error("City seed failed:", err);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}