import prisma from "@/app/lib/db";

// Source: tbl_countries (261 rows). Names are transcribed exactly as they
// appeared in the original data, including a handful with stripped
// diacritics from a charset issue in the source export — e.g. "Cte dIvoire"
// (Côte d'Ivoire), "Runion" (Réunion), "So Tom and Prncipe"
// (São Tomé and Príncipe), "Saint Barthlemy" (Saint Barthélemy). Left as-is
// to match whatever the existing database already has; let me know if you
// want these corrected instead.
const countries: { id: number; countryName: string }[] = [
  { id: 1, countryName: "Afghanistan" },
  { id: 2, countryName: "Albania" },
  { id: 3, countryName: "Algeria" },
  { id: 4, countryName: "American Samoa" },
  { id: 5, countryName: "Andorra" },
  { id: 6, countryName: "Angola" },
  { id: 7, countryName: "Anguilla" },
  { id: 8, countryName: "Antarctica" },
  { id: 9, countryName: "Antigua and Barbuda" },
  { id: 10, countryName: "Argentina" },
  { id: 11, countryName: "Armenia" },
  { id: 12, countryName: "Aruba" },
  { id: 13, countryName: "Australia" },
  { id: 14, countryName: "Austria" },
  { id: 15, countryName: "Azerbaijan" },
  { id: 16, countryName: "Bahamas" },
  { id: 17, countryName: "Bahrain" },
  { id: 18, countryName: "Bangladesh" },
  { id: 19, countryName: "Barbados" },
  { id: 20, countryName: "Belarus" },
  { id: 21, countryName: "Belgium" },
  { id: 22, countryName: "Belize" },
  { id: 23, countryName: "Benin" },
  { id: 24, countryName: "Bermuda" },
  { id: 25, countryName: "Bhutan" },
  { id: 26, countryName: "Bolivia" },
  { id: 27, countryName: "Bosnia and Herzegovina" },
  { id: 28, countryName: "Botswana" },
  { id: 29, countryName: "Bouvet Island" },
  { id: 30, countryName: "Brazil" },
  { id: 31, countryName: "British Antarctic Territory" },
  { id: 32, countryName: "British Indian Ocean Territory" },
  { id: 33, countryName: "British Virgin Islands" },
  { id: 34, countryName: "Brunei" },
  { id: 35, countryName: "Bulgaria" },
  { id: 36, countryName: "Burkina Faso" },
  { id: 37, countryName: "Burundi" },
  { id: 38, countryName: "Cambodia" },
  { id: 39, countryName: "Cameroon" },
  { id: 40, countryName: "Canada" },
  { id: 41, countryName: "Canton and Enderbury Islands" },
  { id: 42, countryName: "Cape Verde" },
  { id: 43, countryName: "Cayman Islands" },
  { id: 44, countryName: "Central African Republic" },
  { id: 45, countryName: "Chad" },
  { id: 46, countryName: "Chile" },
  { id: 47, countryName: "China" },
  { id: 48, countryName: "Christmas Island" },
  { id: 49, countryName: "Cocos [Keeling] Islands" },
  { id: 50, countryName: "Colombia" },
  { id: 51, countryName: "Comoros" },
  { id: 52, countryName: "Congo - Brazzaville" },
  { id: 53, countryName: "Congo - Kinshasa" },
  { id: 54, countryName: "Cook Islands" },
  { id: 55, countryName: "Costa Rica" },
  { id: 56, countryName: "Croatia" },
  { id: 57, countryName: "Cte dIvoire" },
  { id: 58, countryName: "Cuba" },
  { id: 59, countryName: "Cyprus" },
  { id: 60, countryName: "Czech Republic" },
  { id: 61, countryName: "Denmark" },
  { id: 62, countryName: "Djibouti" },
  { id: 63, countryName: "Dominica" },
  { id: 64, countryName: "Dominican Republic" },
  { id: 65, countryName: "Dronning Maud Land" },
  { id: 66, countryName: "East Germany" },
  { id: 67, countryName: "Ecuador" },
  { id: 68, countryName: "Egypt" },
  { id: 69, countryName: "El Salvador" },
  { id: 70, countryName: "Equatorial Guinea" },
  { id: 71, countryName: "Eritrea" },
  { id: 72, countryName: "Estonia" },
  { id: 73, countryName: "Ethiopia" },
  { id: 74, countryName: "Falkland Islands" },
  { id: 75, countryName: "Faroe Islands" },
  { id: 76, countryName: "Fiji" },
  { id: 77, countryName: "Finland" },
  { id: 78, countryName: "France" },
  { id: 79, countryName: "French Guiana" },
  { id: 80, countryName: "French Polynesia" },
  { id: 81, countryName: "French Southern Territories" },
  { id: 82, countryName: "Gabon" },
  { id: 83, countryName: "Gambia" },
  { id: 84, countryName: "Georgia" },
  { id: 85, countryName: "Germany" },
  { id: 86, countryName: "Ghana" },
  { id: 87, countryName: "Gibraltar" },
  { id: 88, countryName: "Greece" },
  { id: 89, countryName: "Greenland" },
  { id: 90, countryName: "Grenada" },
  { id: 91, countryName: "Guadeloupe" },
  { id: 92, countryName: "Guam" },
  { id: 93, countryName: "Guatemala" },
  { id: 94, countryName: "Guernsey" },
  { id: 95, countryName: "Guinea" },
  { id: 96, countryName: "Guinea-Bissau" },
  { id: 97, countryName: "Guyana" },
  { id: 98, countryName: "Haiti" },
  { id: 99, countryName: "Heard Island and McDonald Islands" },
  { id: 100, countryName: "Honduras" },
  { id: 101, countryName: "Hong Kong SAR China" },
  { id: 102, countryName: "Hungary" },
  { id: 103, countryName: "Iceland" },
  { id: 104, countryName: "India" },
  { id: 105, countryName: "Indonesia" },
  { id: 106, countryName: "Iran" },
  { id: 107, countryName: "Iraq" },
  { id: 108, countryName: "Ireland" },
  { id: 109, countryName: "Isle of Man" },
  { id: 110, countryName: "Israel" },
  { id: 111, countryName: "Italy" },
  { id: 112, countryName: "Jamaica" },
  { id: 113, countryName: "Japan" },
  { id: 114, countryName: "Jersey" },
  { id: 115, countryName: "Johnston Island" },
  { id: 116, countryName: "Jordan" },
  { id: 117, countryName: "Kazakhstan" },
  { id: 118, countryName: "Kenya" },
  { id: 119, countryName: "Kiribati" },
  { id: 120, countryName: "Kuwait" },
  { id: 121, countryName: "Kyrgyzstan" },
  { id: 122, countryName: "Laos" },
  { id: 123, countryName: "Latvia" },
  { id: 124, countryName: "Lebanon" },
  { id: 125, countryName: "Lesotho" },
  { id: 126, countryName: "Liberia" },
  { id: 127, countryName: "Libya" },
  { id: 128, countryName: "Liechtenstein" },
  { id: 129, countryName: "Lithuania" },
  { id: 130, countryName: "Luxembourg" },
  { id: 131, countryName: "Macau SAR China" },
  { id: 132, countryName: "Macedonia" },
  { id: 133, countryName: "Madagascar" },
  { id: 134, countryName: "Malawi" },
  { id: 135, countryName: "Malaysia" },
  { id: 136, countryName: "Maldives" },
  { id: 137, countryName: "Mali" },
  { id: 138, countryName: "Malta" },
  { id: 139, countryName: "Marshall Islands" },
  { id: 140, countryName: "Martinique" },
  { id: 141, countryName: "Mauritania" },
  { id: 142, countryName: "Mauritius" },
  { id: 143, countryName: "Mayotte" },
  { id: 144, countryName: "Metropolitan France" },
  { id: 145, countryName: "Mexico" },
  { id: 146, countryName: "Micronesia" },
  { id: 147, countryName: "Midway Islands" },
  { id: 148, countryName: "Moldova" },
  { id: 149, countryName: "Monaco" },
  { id: 150, countryName: "Mongolia" },
  { id: 151, countryName: "Montenegro" },
  { id: 152, countryName: "Montserrat" },
  { id: 153, countryName: "Morocco" },
  { id: 154, countryName: "Mozambique" },
  { id: 155, countryName: "Myanmar [Burma]" },
  { id: 156, countryName: "Namibia" },
  { id: 157, countryName: "Nauru" },
  { id: 158, countryName: "Nepal" },
  { id: 159, countryName: "Netherlands" },
  { id: 160, countryName: "Netherlands Antilles" },
  { id: 161, countryName: "Neutral Zone" },
  { id: 162, countryName: "New Caledonia" },
  { id: 163, countryName: "New Zealand" },
  { id: 164, countryName: "Nicaragua" },
  { id: 165, countryName: "Niger" },
  { id: 166, countryName: "Nigeria" },
  { id: 167, countryName: "Niue" },
  { id: 168, countryName: "Norfolk Island" },
  { id: 169, countryName: "North Korea" },
  { id: 170, countryName: "North Vietnam" },
  { id: 171, countryName: "Northern Mariana Islands" },
  { id: 172, countryName: "Norway" },
  { id: 173, countryName: "Oman" },
  { id: 174, countryName: "Pacific Islands Trust Territory" },
  { id: 175, countryName: "Pakistan" },
  { id: 176, countryName: "Palau" },
  { id: 177, countryName: "Palestinian Territories" },
  { id: 178, countryName: "Panama" },
  { id: 179, countryName: "Panama Canal Zone" },
  { id: 180, countryName: "Papua New Guinea" },
  { id: 181, countryName: "Paraguay" },
  { id: 182, countryName: "People's Democratic Republic of Yemen" },
  { id: 183, countryName: "Peru" },
  { id: 184, countryName: "Philippines" },
  { id: 185, countryName: "Pitcairn Islands" },
  { id: 186, countryName: "Poland" },
  { id: 187, countryName: "Portugal" },
  { id: 188, countryName: "Puerto Rico" },
  { id: 189, countryName: "Qatar" },
  { id: 190, countryName: "Romania" },
  { id: 191, countryName: "Runion" },
  { id: 192, countryName: "Russia" },
  { id: 193, countryName: "Rwanda" },
  { id: 194, countryName: "Saint Barthlemy" },
  { id: 195, countryName: "Saint Helena" },
  { id: 196, countryName: "Saint Kitts and Nevis" },
  { id: 197, countryName: "Saint Lucia" },
  { id: 198, countryName: "Saint Martin" },
  { id: 199, countryName: "Saint Pierre and Miquelon" },
  { id: 200, countryName: "Saint Vincent and the Grenadines" },
  { id: 201, countryName: "Samoa" },
  { id: 202, countryName: "San Marino" },
  { id: 203, countryName: "Saudi Arabia" },
  { id: 204, countryName: "Senegal" },
  { id: 205, countryName: "Serbia" },
  { id: 206, countryName: "Serbia and Montenegro" },
  { id: 207, countryName: "Seychelles" },
  { id: 208, countryName: "Sierra Leone" },
  { id: 209, countryName: "Singapore" },
  { id: 210, countryName: "Slovakia" },
  { id: 211, countryName: "Slovenia" },
  { id: 212, countryName: "So Tom and Prncipe" },
  { id: 213, countryName: "Solomon Islands" },
  { id: 214, countryName: "Somalia" },
  { id: 215, countryName: "South Africa" },
  { id: 216, countryName: "South Korea" },
  { id: 217, countryName: "Spain" },
  { id: 218, countryName: "Sri Lanka" },
  { id: 219, countryName: "Sudan" },
  { id: 220, countryName: "Suriname" },
  { id: 221, countryName: "Svalbard and Jan Mayen" },
  { id: 222, countryName: "Swaziland" },
  { id: 223, countryName: "Sweden" },
  { id: 224, countryName: "Switzerland" },
  { id: 225, countryName: "Syria" },
  { id: 226, countryName: "Taiwan" },
  { id: 227, countryName: "Tajikistan" },
  { id: 228, countryName: "Tanzania" },
  { id: 229, countryName: "Thailand" },
  { id: 230, countryName: "Timor - Leste" },
  { id: 231, countryName: "Togo" },
  { id: 232, countryName: "Tokelau" },
  { id: 233, countryName: "Tonga" },
  { id: 234, countryName: "Trinidad and Tobago" },
  { id: 235, countryName: "Tunisia" },
  { id: 236, countryName: "Turkey" },
  { id: 237, countryName: "Turkmenistan" },
  { id: 238, countryName: "Turks and Caicos Islands" },
  { id: 239, countryName: "Tuvalu" },
  { id: 240, countryName: "U.S. Minor Outlying Islands" },
  { id: 241, countryName: "U.S. Miscellaneous Pacific Islands" },
  { id: 242, countryName: "U.S. Virgin Islands" },
  { id: 243, countryName: "Uganda" },
  { id: 244, countryName: "Ukraine" },
  { id: 245, countryName: "Union of Soviet Socialist Republics" },
  { id: 246, countryName: "United Arab Emirates" },
  { id: 247, countryName: "United Kingdom" },
  { id: 248, countryName: "United States" },
  { id: 249, countryName: "Unknown or Invalid Region" },
  { id: 250, countryName: "Uruguay" },
  { id: 251, countryName: "Uzbekistan" },
  { id: 252, countryName: "Vanuatu" },
  { id: 253, countryName: "Vatican City" },
  { id: 254, countryName: "Venezuela" },
  { id: 255, countryName: "Vietnam" },
  { id: 256, countryName: "Wake Island" },
  { id: 257, countryName: "Wallis and Futuna" },
  { id: 258, countryName: "Western Sahara" },
  { id: 259, countryName: "Yemen" },
  { id: 260, countryName: "Zambia" },
  { id: 261, countryName: "Zimbabwe" },
];

export async function seedCountries() {
  const result = await prisma.country.createMany({
    data: countries,
    skipDuplicates: true,
  });
  console.log(`Seeded ${result.count} countries.`);
}

if (require.main === module) {
  seedCountries()
    .catch((err) => {
      console.error("Country seed failed:", err);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}